package:
  name: cubeviz
  version: {{version}}

{{source}}

build:
  noarch: python
  number: 3
  script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - cubeviz = cubeviz.cubeviz:main

requirements:

  build:
    - python >=3
    - setuptools
    - setuptools_scm

  run:
    - python >=3
    - asdf
    - asteval
    - astropy
    - glue-core >=0.13.0,<0.13.999
    - numpy
    - pytest
    - specviz <0.5.999
    - spectral-cube >=0.4.2

about:
    home: https://github.com/spacetelescope/cubeviz
    license: BSD
    summary: Data analysis package for cubes.

test:
  imports:
    - cubeviz
  commands:
    - cubeviz --help
