package:
  name: cubeviz
  version: {{version}}

{{source}}

build:
  noarch: python
  number: 2
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - cubeviz = cubeviz.cubeviz:main

requirements:

  build:
    - python >=3
    - setuptools

  run:
    - python >=3
    - asdf
    - asteval
    - astropy
    - glue-core >=0.13.0
    - numpy
    - pytest
    - specviz <0.6
    - spectral-cube >=0.4.2

about:
    home: https://github.com/spacetelescope/cubeviz
    license: BSD
    summary: Data analysis package for cubes.

test:
  imports:
    - cubeviz
  commands:
    - cubeviz --help
