package:
  name: glue-geospatial
  version: {{version}}

{{source}}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:

  build:
    - python
    - setuptools

  run:
    - python
    # Numpy needs to be pinned to 1.12 (the latest version that
    # there is a rasterio package for) otherwise there is a
    # conflict according to conda
    - numpy 1.12.*
    - astropy
    - pyproj
    - rasterio
    - affine
    - glue-core >=0.12

test:
  imports:
    - glue_geospatial
    - glue_geospatial.data_factory
    - glue_geospatial.coordinates

about:
  home: https://github.com/glue-viz/glue-geospatial
  license: BSD 3-Clause
  summary: Geospatial plugin for glue

extra:
  recipe-maintainers:
    - astrofrog
