language: c

sudo: false

os:
    - osx
    - linux

env:
  matrix:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.5
    - PYTHON_VERSION=3.6
  global:
    - CONDA_DEPENDENCIES='jinja2 pyqt'

before_install:

  # Install ci-helpers and set up conda
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh

  # Clone repositories
  - git clone git://github.com/glue-viz/glue.git glue-core
  - git clone git://github.com/glue-viz/glue-vispy-viewers.git
  - git clone git://github.com/glue-viz/glueviz.git

script:

    # The following puts the correct version numbers in the recipes
    - python prepare_recipes.py

    - source activate root
    - conda install conda-build anaconda-client
    - conda config --set anaconda_upload no

    - cd recipes

    - conda build --python $PYTHON_VERSION glue-core
    - conda build glue-core --output
    - anaconda -t $ANACONDA_TOKEN upload --force -l dev "$(conda build glue-core --output)"

    - conda build --python $PYTHON_VERSION glue-vispy-viewers
    - conda build glue-vispy-viewers --output
    - anaconda -t $ANACONDA_TOKEN upload --force -l dev "$(conda build glue-vispy-viewers --output)"

    - conda build --python $PYTHON_VERSION glueviz
    - conda build glueviz --output
    - anaconda -t $ANACONDA_TOKEN upload --force -l dev "$(conda build glueviz --output)"$


