language: c

sudo: false

os:
  - linux
  - osx
  - windows

env:
  matrix:
    - PYTHON_VERSION=3.6
    - PYTHON_VERSION=3.7
    - PYTHON_VERSION=3.8
  global:
    - MAMBA=True
    - PACKAGES_GLUEVIZ="glueviz>=1.0 glue-wwt"
    - PACKAGES_CONDAFORGE="glueviz>=1.0"

before_install:
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh

script:
  - if [[ $TRAVIS_OS_NAME != windows ]]; then mamba create -n test-stable-mamba -c glueviz python=$PYTHON_VERSION $PACKAGES_GLUEVIZ; fi
  - if [[ $TRAVIS_OS_NAME != windows ]]; then mamba create -n test-dev-mamba -c glueviz/label/dev python=$PYTHON_VERSION $PACKAGES_GLUEVIZ; fi
  - if [[ $TRAVIS_OS_NAME != windows ]]; then mamba create -n test-cf-mamba -c conda-forge python=$PYTHON_VERSION $PACKAGES_CONDAFORGE; fi
  - conda create -n test-stable-conda -c glueviz python=$PYTHON_VERSION $PACKAGES_GLUEVIZ
  - conda create -n test-dev-conda -c glueviz/label/dev python=$PYTHON_VERSION $PACKAGES_GLUEVIZ
  - conda create -n test-cf-conda -c conda-forge python=$PYTHON_VERSION $PACKAGES_CONDAFORGE
