language: c

sudo: false

os:
    - osx

env:
  global:
    - CONDA_DEPENDENCIES='jinja2 pyqt requests=2.18.4'
    - PYTHON_VERSION=3.6

before_install:
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh

script:
  - ./build_all.sh
