package:
  name: glue-medical
  version: {{version}}

{{source}}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:

  build:
    - python
    - setuptools

  run:

    - python
    - gdcm  # [not osx]
    - pydicom
    - glue-core >=0.12

    # For some reason, when on Windows with Python 2.7, conda tries to install
    # an older version of PyQt5 with sip 4.19 which causes issues
    - sip 4.18.*  # [win and py27]

test:
 imports:
   - glue_medical
   - glue_medical.dicom_factory
   - glue_medical.dicom_importer

about:
  home: https://github.com/glue-viz/glue-medical
  license: BSD 3-Clause
  summary: Medical plugin for glue

extra:
  recipe-maintainers:
    - astrofrog
