package:
  name: glue-medical
  version: {{version}}

{{source}}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:

  build:
    - python
    - setuptools

  run:
    - python
    - glue-core >=0.12
    - gdcm
    - pydicom

test:
  imports:
    - glue_medical
    - glue_medical.dicom_factory
    - glue_medical.dicom_importer

about:
  home: https://github.com/glue-viz/glue-medical
  license: BSD 3-Clause
  summary: Medical plugin for glue

extra:
  recipe-maintainers:
    - astrofrog
