package:
  name: glue-medical
  version: {{version}}

{{source}}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:

  build:
    - python
    - setuptools >=30.3
    - setuptools_scm

  run:
    - python
    - gdcm  # [py27 or not osx]
    - pydicom
    - glue-core >=0.12

test:
 imports:
   - glue_medical
   - glue_medical.dicom_factory
   - glue_medical.dicom_importer

about:
  home: https://github.com/glue-viz/glue-medical
  license: BSD 3-Clause
  summary: Medical plugin for glue

extra:
  recipe-maintainers:
    - astrofrog
