# NOTE: this is a meta-package that includes the core glue code as well as stable
# plugins. This is the main conda package we want in the Navigator, so we add the
# app: entry here and not in the glue-core package. Even though glueviz is a
# Python package on PyPI, and has a setup.py file, we don't include a build command
# below since the only purpose of that command is to trigger the installation of the
# dependencies.

package:
  name: glueviz
  version: {{version}}

source:
  path: ../../glueviz

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:

  # Note that we can't do >=0.11 and >=0.8 here because 0.11.dev counts as less than
  # 0.11 for example, so we use .999 instead as a workaround.
  run:
    - glue-core >0.10.999
    - glue-vispy-viewers >=0.7.999

test:
  commands:
    - glue --version
    - glue-deps list

app:
  entry: glue
  icon: logo.png
  summary: Multi-dimensional linked data exploration
  type: desk

about:
  home: http://glueviz.org
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Multi-dimensional linked data exploration

extra:
  recipe-maintainers:
    - astrofrog
