version: 2

jobs:
  build:
    docker:
      - image: continuumio/miniconda3:4.3.27
    steps:
      - checkout
      - run:
          name: Installing OpenGL
          command: |
            apt update
            apt -y install libgl1-mesa-swx11
      - run:
          name: Installing Gtk2
          command: |
            apt -y install libgtk2.0-dev
      - run:
          name: Conda setup
          command: |
            conda config --set always_yes yes --set changeps1 no
            conda install jinja2 pyqt requests
      - run:
          name: Build packages
          command: ./build_all.sh

workflows:
   version: 2
   nightly:
     triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - build

   build_and_test:
     jobs:
       - build
