version: 2

jobs:
  build:
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - run:
          name: Installing required libraries
          command: |
            apt update
            apt -y install libgtk2.0-dev libgl1-mesa-glx libegl1-mesa libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6
      - run:
          name: Conda setup
          command: |
            conda config --set always_yes yes --set changeps1 no
            conda install jinja2 pyqt requests=2.18.4
      - run:
          name: Build packages
          command: ./build_all.sh

workflows:
   version: 2
   nightly:
     triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - build

   build_and_test:
     jobs:
       - build
