version: 2

jobs:
  build:
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - run:
          name: Conda setup
          command: jinja2 pyqt requests
      - run:
          name: Build packages
          command: PYTHON_VERSION=3.6 STABLE=true ./build_packages.sh

