package:
  name: specviz
  version: {{version}}

{{source}}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt --offline --no-git
  entry_points:
    - specviz = specviz.app:start

requirements:
  build:
    - python >=3.5
    - setuptools

  run:
    - python >=3.5
    - astropy >=3.0
    - pyqt >=5.6
    - pyqtgraph >=0.10.0
    - qtawesome
    - qtpy
    - specutils >=0.5.1
    - click
    - pytest
    - asteval

test:
  imports:
    - specviz
    - specviz.core
    - specviz.data
    - specviz.extern
    - specviz.io
    - specviz.plugins
    - specviz.tests
    - specviz.third_party
    - specviz.utils
    - specviz.widgets

about:
  home: https://github.com/spacetelescope/specviz
  license: BSD

test:
  imports:
    - specviz
