package:
  name: specviz
  version: {{version}}

{{source}}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - specviz = specviz.app:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - astropy
    - pyqt >=5.6
    - pyqtgraph >=0.10.0
    - qtawesome
    - qtpy
    - specutils >=0.4
    - click
    - pytest
    - asteval

test:
  imports:
    - specviz
    - specviz.core
    - specviz.data
    - specviz.extern
    - specviz.io
    - specviz.plugins
    - specviz.tests
    - specviz.third_party
    - specviz.utils
    - specviz.widgets

about:
  home: https://github.com/spacetelescope/specviz
  license: BSD

test:
  imports:
    - specviz
