package:
  name: glueviz
  version: {{version}}

source:
  path: ../../glue

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  osx_is_app: True

requirements:

  build:
    - python

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - astropy
    - ipython
    - ipykernel
    - h5py
    - pandas
    - pyqt
    - qtconsole
    - xlrd
    - scikit-image
    - python.app  # [osx]

test:
  requires:
    - mock
    - pytest
  imports:
    - glue
  commands:
    - glue --version
    - glue-deps list

app:
  entry: glue
  icon: logo.png
  summary: Multi-dimensional linked data exploration
  type: desk

about:
  home: http://glueviz.org
  license: BSD 3-Clause
  summary: Multi-dimensional linked data exploration

extra:
  recipe-maintainers:
    - astrofrog
