package:
  name: glue-wwt
  version: {{version}}

{{source}}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:

  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - glue-core >0.10.999
    - astropy
    - matplotlib
    - requests

test:
  imports:
    - glue_wwt

about:
  home: https://github.com/glue-viz/glue-wwt
  license: BSD 3-Clause
  summary: WWT viewer plugin for glue

extra:
  recipe-maintainers:
    - astrofrog
