package:
  name: py-expression-eval
  version: {{version}}

{{source}}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:

  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - py_expression_eval

about:
  home: https://github.com/Axiacore/py-expression-eval
  license: MIT
  description: Python Mathematical Expression Evaluator

extra:
  recipe-maintainers:
    - astrofrog
