package:
  name: mosviz
  version: {{version}}

{{source}}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt --offline --no-git

requirements:

  build:
    - python >=3.5
    - setuptools

  run:
    - python >=3.5
    - numpy
    - astropy >=3.0
    - glue-core >=0.13.0
    - qtpy
    - regions >=0.3
    - specviz >=0.6.2

about:
    home: https://github.com/spacetelescope/mosviz
    license: BSD
    summary: Quick-look analysis and visualization tool for multi-object spectroscopy

test:
  imports:
    - mosviz
